
#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtoLnJhbWluNjlAZ21haWwuY29tIiwiaWF0IjoxNjMwNDI4MDI1LCJleHAiOjE2MzA0Mjg5MjV9.51H0xmJSWwextHax8iXrjL0QZdjReNLXNOZLvmVwxiY

POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    
    "email": "kh.ramin69@gmail.com",
    "password": "hhgj8876" 
}



# POST http://localhost:3001/v1/user
# Content-Type: application/json

#   {
#       "name": "Ramin khodaie",
#     "compony": "bornamehrfan",
#     "address": "tabriz",
#     "phonenumber": "2345678",
#     "email": "kh.ramin69@gmail.com",
#     "password": "hhgj8876" 
# }

